"""initial_schema

Revision ID: 4fcb1627c45b
Revises: 
Create Date: 2026-09-20 08:20:22.015108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcb1627c45b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='hospitalstatus'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_slug'), 'hospitals', ['slug'], unique=True)
    op.create_index(op.f('ix_hospitals_status'), 'hospitals', ['status'], unique=False)
    op.create_table('operational_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_events_correlation_id'), 'operational_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_operational_events_event_type'), 'operational_events', ['event_type'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('platform_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'HOSPITAL_ADMIN', 'DOCTOR', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('operation_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_hospital_id'), 'audit_events', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_audit_events_operation_id'), 'audit_events', ['operation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_hospital_id'), 'departments', ['hospital_id'], unique=False)
    op.create_table('external_identifier_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('internal_entity_type', sa.String(length=50), nullable=False),
    sa.Column('internal_id', sa.String(length=36), nullable=False),
    sa.Column('external_system_name', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_identifier_mappings_external_id'), 'external_identifier_mappings', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_identifier_mappings_hospital_id'), 'external_identifier_mappings', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_external_identifier_mappings_internal_entity_type'), 'external_identifier_mappings', ['internal_entity_type'], unique=False)
    op.create_index(op.f('ix_external_identifier_mappings_internal_id'), 'external_identifier_mappings', ['internal_id'], unique=False)
    op.create_table('healthcare_system_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_system_connections_hospital_id'), 'healthcare_system_connections', ['hospital_id'], unique=False)
    op.create_table('hospital_staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_hospital_staff_hospital_id'), 'hospital_staff', ['hospital_id'], unique=False)
    op.create_table('integration_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('operation_id', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_operations_correlation_id'), 'integration_operations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_integration_operations_hospital_id'), 'integration_operations', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_integration_operations_operation_id'), 'integration_operations', ['operation_id'], unique=False)
    op.create_index(op.f('ix_integration_operations_operation_type'), 'integration_operations', ['operation_type'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('insurance_info', sa.JSON(), nullable=False),
    sa.Column('emergency_contact', sa.JSON(), nullable=False),
    sa.Column('external_patient_id', sa.String(length=100), nullable=True),
    sa.Column('primary_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_external_patient_id'), 'patients', ['external_patient_id'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('reconciliation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('operation_id', sa.String(length=100), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=False),
    sa.Column('last_known_state', sa.String(length=50), nullable=False),
    sa.Column('verification_attempts', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'ESCALATED', name='reconciliationstatus'), nullable=False),
    sa.Column('escalated_to_human', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_records_appointment_id'), 'reconciliation_records', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_correlation_id'), 'reconciliation_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_hospital_id'), 'reconciliation_records', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_operation_id'), 'reconciliation_records', ['operation_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_status'), 'reconciliation_records', ['status'], unique=False)
    op.create_table('specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_hospital_id'), 'specialties', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_specialties_name'), 'specialties', ['name'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('preferred_communication_channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('notification_opt_in', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preferred_hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_trigger', sa.String(length=100), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_event_trigger'), 'workflows', ['event_trigger'], unique=False)
    op.create_index(op.f('ix_workflows_hospital_id'), 'workflows', ['hospital_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_hospital_id'), 'ai_conversations', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_patient_id'), 'ai_conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('specialty_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('qualifications', sa.String(length=255), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('consultation_types', sa.JSON(), nullable=False),
    sa.Column('appointment_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='doctorstatus'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctors_external_provider_id'), 'doctors', ['external_provider_id'], unique=False)
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_specialty_id'), 'doctors', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_doctors_status'), 'doctors', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('notification_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_hospital_id'), 'notifications', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRIED', name='workflowstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_hospital_id'), 'workflow_executions', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_trigger_event'), 'workflow_executions', ['trigger_event'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('ai_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('current_intent', sa.String(length=100), nullable=True),
    sa.Column('selected_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('selected_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('selected_slot', sa.JSON(), nullable=False),
    sa.Column('current_appointment_id', sa.String(length=36), nullable=True),
    sa.Column('relevant_preferences', sa.JSON(), nullable=False),
    sa.Column('workflow_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('ai_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('safety_passed', sa.Boolean(), nullable=False),
    sa.Column('medical_escalation_triggered', sa.Boolean(), nullable=False),
    sa.Column('hallucination_check_passed', sa.Boolean(), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_evaluations_conversation_id'), 'ai_evaluations', ['conversation_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('tool_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PENDING', 'CONFIRMED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'FAILED', 'SYNCHRONIZATION_PENDING', 'RECONCILIATION_REQUIRED', name='appointmentstatus'), nullable=False),
    sa.Column('consultation_type', sa.Enum('IN_PERSON', 'VIDEO', 'PHONE', name='consultationtype'), nullable=False),
    sa.Column('reason_for_visit', sa.String(length=255), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_appointment_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('operation_id', sa.String(length=100), nullable=True),
    sa.Column('appointment_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_correlation_id'), 'appointments', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_end_time'), 'appointments', ['end_time'], unique=False)
    op.create_index(op.f('ix_appointments_external_appointment_id'), 'appointments', ['external_appointment_id'], unique=False)
    op.create_index(op.f('ix_appointments_hospital_id'), 'appointments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_appointments_idempotency_key'), 'appointments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_appointments_operation_id'), 'appointments', ['operation_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('blocked_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_slots_doctor_id'), 'blocked_slots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_blocked_slots_end_time'), 'blocked_slots', ['end_time'], unique=False)
    op.create_index(op.f('ix_blocked_slots_hospital_id'), 'blocked_slots', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_blocked_slots_start_time'), 'blocked_slots', ['start_time'], unique=False)
    op.create_table('calendars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_index(op.f('ix_calendars_hospital_id'), 'calendars', ['hospital_id'], unique=False)
    op.create_table('capability_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('operation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_executions_capability_name'), 'capability_executions', ['capability_name'], unique=False)
    op.create_index(op.f('ix_capability_executions_conversation_id'), 'capability_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_capability_executions_correlation_id'), 'capability_executions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_capability_executions_operation_id'), 'capability_executions', ['operation_id'], unique=False)
    op.create_table('questionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specialty_id', sa.String(length=36), nullable=True),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_doctor_id'), 'questionnaires', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_questionnaires_hospital_id'), 'questionnaires', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_questionnaires_specialty_id'), 'questionnaires', ['specialty_id'], unique=False)
    op.create_table('appointment_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=False),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_history_appointment_id'), 'appointment_history', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_history_hospital_id'), 'appointment_history', ['hospital_id'], unique=False)
    op.create_table('availabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilities_calendar_id'), 'availabilities', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_availabilities_hospital_id'), 'availabilities', ['hospital_id'], unique=False)
    op.create_table('integration_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('external_appointment_id', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_verifications_appointment_id'), 'integration_verifications', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_integration_verifications_external_appointment_id'), 'integration_verifications', ['external_appointment_id'], unique=False)
    op.create_index(op.f('ix_integration_verifications_hospital_id'), 'integration_verifications', ['hospital_id'], unique=False)
    op.create_table('questionnaire_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('YES_NO', 'CHOICE', 'MULTIPLE_CHOICE', 'NUMERIC', 'DATE', 'SHORT_TEXT', 'LONG_TEXT', 'STRUCTURED', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_questions_questionnaire_id'), 'questionnaire_questions', ['questionnaire_id'], unique=False)
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_responses_appointment_id'), 'questionnaire_responses', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_responses_hospital_id'), 'questionnaire_responses', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_responses_patient_id'), 'questionnaire_responses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_responses_questionnaire_id'), 'questionnaire_responses', ['questionnaire_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_responses_questionnaire_id'), table_name='questionnaire_responses')
    op.drop_index(op.f('ix_questionnaire_responses_patient_id'), table_name='questionnaire_responses')
    op.drop_index(op.f('ix_questionnaire_responses_hospital_id'), table_name='questionnaire_responses')
    op.drop_index(op.f('ix_questionnaire_responses_appointment_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    op.drop_index(op.f('ix_questionnaire_questions_questionnaire_id'), table_name='questionnaire_questions')
    op.drop_table('questionnaire_questions')
    op.drop_index(op.f('ix_integration_verifications_hospital_id'), table_name='integration_verifications')
    op.drop_index(op.f('ix_integration_verifications_external_appointment_id'), table_name='integration_verifications')
    op.drop_index(op.f('ix_integration_verifications_appointment_id'), table_name='integration_verifications')
    op.drop_table('integration_verifications')
    op.drop_index(op.f('ix_availabilities_hospital_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_calendar_id'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_index(op.f('ix_appointment_history_hospital_id'), table_name='appointment_history')
    op.drop_index(op.f('ix_appointment_history_appointment_id'), table_name='appointment_history')
    op.drop_table('appointment_history')
    op.drop_index(op.f('ix_questionnaires_specialty_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_hospital_id'), table_name='questionnaires')
    op.drop_index(op.f('ix_questionnaires_doctor_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_capability_executions_operation_id'), table_name='capability_executions')
    op.drop_index(op.f('ix_capability_executions_correlation_id'), table_name='capability_executions')
    op.drop_index(op.f('ix_capability_executions_conversation_id'), table_name='capability_executions')
    op.drop_index(op.f('ix_capability_executions_capability_name'), table_name='capability_executions')
    op.drop_table('capability_executions')
    op.drop_index(op.f('ix_calendars_hospital_id'), table_name='calendars')
    op.drop_table('calendars')
    op.drop_index(op.f('ix_blocked_slots_start_time'), table_name='blocked_slots')
    op.drop_index(op.f('ix_blocked_slots_hospital_id'), table_name='blocked_slots')
    op.drop_index(op.f('ix_blocked_slots_end_time'), table_name='blocked_slots')
    op.drop_index(op.f('ix_blocked_slots_doctor_id'), table_name='blocked_slots')
    op.drop_table('blocked_slots')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_operation_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_idempotency_key'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_hospital_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_external_appointment_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_end_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_correlation_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_evaluations_conversation_id'), table_name='ai_evaluations')
    op.drop_table('ai_evaluations')
    op.drop_table('ai_contexts')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_trigger_event'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_hospital_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_hospital_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_doctors_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_specialty_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_external_provider_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_patient_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_hospital_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_workflows_hospital_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_event_trigger'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_specialties_name'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_hospital_id'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_reconciliation_records_status'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_operation_id'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_hospital_id'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_correlation_id'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_appointment_id'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_external_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_integration_operations_operation_type'), table_name='integration_operations')
    op.drop_index(op.f('ix_integration_operations_operation_id'), table_name='integration_operations')
    op.drop_index(op.f('ix_integration_operations_hospital_id'), table_name='integration_operations')
    op.drop_index(op.f('ix_integration_operations_correlation_id'), table_name='integration_operations')
    op.drop_table('integration_operations')
    op.drop_index(op.f('ix_hospital_staff_hospital_id'), table_name='hospital_staff')
    op.drop_table('hospital_staff')
    op.drop_index(op.f('ix_healthcare_system_connections_hospital_id'), table_name='healthcare_system_connections')
    op.drop_table('healthcare_system_connections')
    op.drop_index(op.f('ix_external_identifier_mappings_internal_id'), table_name='external_identifier_mappings')
    op.drop_index(op.f('ix_external_identifier_mappings_internal_entity_type'), table_name='external_identifier_mappings')
    op.drop_index(op.f('ix_external_identifier_mappings_hospital_id'), table_name='external_identifier_mappings')
    op.drop_index(op.f('ix_external_identifier_mappings_external_id'), table_name='external_identifier_mappings')
    op.drop_table('external_identifier_mappings')
    op.drop_index(op.f('ix_departments_hospital_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_operation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_hospital_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_operational_events_event_type'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_correlation_id'), table_name='operational_events')
    op.drop_table('operational_events')
    op.drop_index(op.f('ix_hospitals_status'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_slug'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
